FROM node:20-alpine

WORKDIR /app

# Dependencias del sistema necesarias para Prisma + bcrypt
RUN apk add --no-cache openssl python3 make g++

COPY package.json ./
COPY tsconfig.json ./

RUN npm install

COPY prisma ./prisma
COPY src ./src

RUN npx prisma generate

EXPOSE 4000

CMD ["npm", "run", "dev"]
